class BulletRotationalLimitMotor:
    def setMaxMotorForce(self, force: float) -> None: ...

    def setTargetVelocity(self, velocity: float) -> None: ...

    def setMotorEnabled(self, enable: bool) -> None: ...
