from ..core import PandaNode

class BulletDebugNode(PandaNode):
    def __init__(self, name: str = 'debug'): ...

    def showBoundingBoxes(self, show: bool) -> None: ...

    def showConstraints(self, show: bool) -> None: ...

    def showNormals(self, show: bool) -> None: ...

    def showWireframe(self, show: bool) -> None: ...
