class LVecBase3f:
    def __add__(self, other: LVecBase3f) -> LVecBase3f: ...

    def __sub__(self, other: LVecBase3f) -> LVecBase3f: ...

    def __mul__(self, scalar: float) -> LVecBase3f: ...

    def __iadd__(self, other: LVecBase3f) -> LVecBase3f: ...

    def __imul__(self, scalar: float) -> LVecBase3f: ...

    def __getitem__(self, i: int) -> float: ...

    def cross(self, other: LVecBase3f) -> LVecBase3f: ...

    def dot(self, other: LVecBase3f) -> float: ...

    def length(self) -> float: ...

    def normalized(self) -> LVecBase3f: ...
