from .PandaNode import PandaNode
from .Thread import Thread
from .DrawMask import DrawMask
from .LPoint3f import LPoint3f
from .LMatrix4f import LMatrix4f

class NodePath:
    def node(self) -> PandaNode: ...

    def attachNewNode(self, node: PandaNode, sort: int = 0, current_thread: Thread = ...) -> NodePath: ...

    def setPos(self, x: float, y: float, z: float) -> None: ...

    def lookAt(self, x: float, y: float, z: float) -> None: ...

    def hide(self) -> None: ...

    def show(self) -> None: ...

    def isHidden(self, camera_mask: DrawMask = ...) -> bool: ...

    def reparentTo(self, other: NodePath, sort: int = 0, current_thread: Thread = ...) -> None: ...

    def getPos(self) -> LPoint3f: ...

    def getMat(self, other: NodePath) -> LMatrix4f: ...
